--
-- LEW-19710-1, CCSDS SOIS Electronic Data Sheet Implementation
--
-- Copyright (c) 2020 United States Government as represented by
-- the Administrator of the National Aeronautics and Space Administration.
-- All Rights Reserved.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--    http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--


-- -------------------------------------------------------------------------
-- Prepare for any follow-on scripts by loading the EDS DB that was generated
-- in the previous steps, so the objects can be generated and maniplulated with
-- the same implementation that runtime/FSW would use.  
--
-- After this script completes, "SEDS.edslib" should be a fully-functioning
-- set of Lua bindings for the EDS objects just as it would be in an external tool,
-- and thus it can be used to instantiate EDS-described objects that will be
-- compatible with future Flight Software code.
-- -------------------------------------------------------------------------

local makefilename = SEDS.to_filename("db_objects.mk")
local objdir = SEDS.get_define("OBJDIR") or "./obj"
local srcdir = SEDS.get_define("SRCDIR") or "./src"
local edsdb_basename = string.format("%s/%s", objdir, SEDS.to_filename("db"))
local edsdb_load_sym = string.upper(SEDS.get_define("EDSTOOL_PROJECT_NAME") or "EDS") .. "_DATABASE"

-- ------------------------------------------------------------------
-- Step 0: determine list of targets to build here.
-- there are potentially 3 targets:
--    .a   - static link version
--    .so  - shared link version (PIC)
--    .obj - relocatable version
-- ------------------------------------------------------------------
local all_edsdb_targets = {}
for _,t in ipairs({ ".so", ".a", ".obj" }) do
  all_edsdb_targets[1 + #all_edsdb_targets] = edsdb_basename .. t
end


-- ------------------------------------------------------------------
-- Step 1: call the build tool to actually run the makefile generated by the edsdb script
--
-- This should produce a valid .a and .so file.  If this triggers any errors,
-- the script will abort.  This indicates problems in the generated source files.
-- ------------------------------------------------------------------
SEDS.execute_tool("MAKE_PROGRAM",
  string.format("-C \"%s\" -f \"%s\" O=\"%s\" S=\"%s\" %s",
    SEDS.get_define("EDSTOOL_OUTPUT_DIR") or ".",
    makefilename,
    objdir,
    srcdir,
    table.concat(all_edsdb_targets," ")
  )
)

-- ------------------------------------------------------------------
-- Step 2: load the .so file just created into this running process
-- The database will be attached to the "SEDS" global as the edslib member
-- ------------------------------------------------------------------
SEDS.edsdb = SEDS.load_plugin(edsdb_basename .. ".so");
SEDS.edslib = SEDS.attach_db(SEDS.edsdb[edsdb_load_sym])

