#####################################################
# 
# CFE/CFS target build makefile helper
# This builds the EDS database objects for the target processor
# 
# Importantly - the EDS tool is not re-invoked here.  This simply calls
# the makefile that was generated previously when the tool was executed
# during the "mission-prebuild" phase.  It uses a different "buildenv"
# file that (may) point to a different compiler, and a different "O"
# directory to put the object files into the correct arch-specific subdir.
#
#####################################################

# This checks the sanity of the calling environment.  If any of these fail
# it indicates a problem in the CMake target that invokes this makefile.
ifeq ($(EDSTOOL_PROJECT_NAME),)
$(error EDSTOOL_PROJECT_NAME is not defined)
endif
ifeq ($(BUILD_CONFIG),)
$(error BUILD_CONFIG not defined)
endif
ifeq ($(O),)
$(error O is not defined)
endif
ifeq ($(S),)
$(error S is not defined)
endif

# now include the files that should provide all the needed context
include edstool-namespace-$(EDSTOOL_PROJECT_NAME).mk
include $(O)/edstool-buildenv.mk $(wildcard $(O)/*.d)

EDSTOOL_ARCH := $(firstword $(subst ;, ,$(BUILD_CONFIG)))

# using "wildcard" here makes it evaulate to an empty string if the file does not exist
DBOBJ_MAKEFILE   := $(wildcard $(EDSTOOL_OUTPUT_DIR)/$(EDS_FILE_PREFIX)_db_objects.mk)
INTFOBJ_MAKEFILE := $(wildcard $(EDSTOOL_OUTPUT_DIR)/$(EDS_FILE_PREFIX)_sb_dispatchdb_objects.mk)

# These makefiles should have been generated by the top-level build
include $(DBOBJ_MAKEFILE) $(INTFOBJ_MAKEFILE)

.PHONY: all db_objects sb_dispatchdb_objects
all: db_objects sb_dispatchdb_objects
	@echo All target-specific EDS objects built

db_objects: $(addprefix $(O)/$(EDS_FILE_PREFIX)_db,$(SHARED_SUFFIX) $(STATIC_SUFFIX))
sb_dispatchdb_objects: $(addprefix $(O)/$(EDS_FILE_PREFIX)_sb_dispatchdb,$(SHARED_SUFFIX) $(STATIC_SUFFIX))

