include edstool-buildenv.d

# The O variable in this context is localized; should not use O from the parent here.
O := $(OBJDIR)
EDSTOOL_ARCH := $(firstword $(subst ;, ,$(BUILD_CONFIG)))

LOCAL_STAMPFILE  := $(MISSION_BINARY_DIR)/edstool-complete.stamp
DBOBJ_MAKEFILE   := $(MISSION_BINARY_DIR)/$(EDS_FILE_PREFIX)_db_objects.mk
INTFOBJ_MAKEFILE := $(MISSION_BINARY_DIR)/$(EDS_FILE_PREFIX)_interfacedb_objects.mk

.PHONY: all db_objects interfacedb_objects
all: db_objects interfacedb_objects
	@echo All target-specific EDS objects built

# The stampfile dependency here should have been generated by the top-level (mission scope)
# build procedures before this build was invoked.  It is listed here mainly as a sanity check.
db_objects interfacedb_objects: $(LOCAL_STAMPFILE)

db_objects: $(addprefix $(OBJDIR)/$(EDS_FILE_PREFIX)_db,$(SHARED_SUFFIX) $(STATIC_SUFFIX))
interfacedb_objects: $(addprefix $(OBJDIR)/$(EDS_FILE_PREFIX)_interfacedb,$(SHARED_SUFFIX) $(STATIC_SUFFIX))

# These makefiles should have been generated by the top-level build
include $(DBOBJ_MAKEFILE) $(INTFOBJ_MAKEFILE)
