###########################################################
#
# EDS CFE mission build setup
#
# This file is evaluated as part of the "prepare" stage
# and can be used to set up prerequisites for the build,
# such as generating header files
#
###########################################################


include(${MISSION_SOURCE_DIR}/tools/eds/tool/cmake/edstool-execute-target.cmake)

#
# When including this script from a top-level mission build,
# also generate the required build system files.  These are
# the same across all CPUs so there is no reason to repeat this
# in the arch-specific builds.
#
function (find_cfs_app_dirs OUT_LIST)

  # Now that a complete list of mission dependencies is generated,
  # check for the presence of additional special files under each app subdir:
  #  - Electronic Data Sheet XML source files under eds/ subdirectory
  #  - Electronic Data Sheet toolchain plugin scripts also under eds/ subdirectory
  #  - The "functional-test" subdir will be installed to the host functional test dir
  #  - The "ui" subdir will be installed to the UI pages install dir
  set(OUT_LIST_LOCAL)
  foreach(APP ${ARGN})
    set(APPSRC ${${APP}_MISSION_DIR})
    list(APPEND OUT_LIST_LOCAL ${APPSRC})

    if (IS_DIRECTORY ${APPSRC}/functional-test AND DEFINED FT_INSTALL_SUBDIR)
      install(DIRECTORY ${APPSRC}/functional-test/ DESTINATION ${FT_INSTALL_SUBDIR})
    endif ()

    if (IS_DIRECTORY ${APPSRC}/ui AND DEFINED UI_INSTALL_SUBDIR)
      install(DIRECTORY ${APPSRC}/ui/ DESTINATION ${UI_INSTALL_SUBDIR}/pages)
    endif()
  endforeach()

  set(${OUT_LIST} ${OUT_LIST_LOCAL} PARENT_SCOPE)

endfunction (find_cfs_app_dirs)

# Capture the set of EDS source files present in the build tree
find_cfs_app_dirs(APP_DIRLIST ${MISSION_DEPS})
edstool_find_eds_sources(
    ${MISSION_NAME} ${MISSION_BINARY_DIR}
    ${MISSION_DEFS} ${APP_DIRLIST}
)

# This function will add a target called "edstool-execute"
# However it will not set up a dependency on that target (this is done below)
edstool_setup_toplevel(edstool-execute
  ${MISSION_NAME} ${MISSION_BINARY_DIR}
)

# Generate a list of CPU targets
set(TGTNAMELIST "/* Automatically generated from targets.cmake - do not edit this file directly */\n\n")
if(DEFINED MISSION_CPUNAMES)
    foreach(CPUNAME ${MISSION_CPUNAMES})
        set(TGTNAMELIST "${TGTNAMELIST}DEFINE_TGTNAME(${CPUNAME})\n")
    endforeach()
else()
    set(TGTID 1)
    while(DEFINED TGT${TGTID}_NAME)
        set(TGTNAMELIST "${TGTNAMELIST}DEFINE_TGTNAME(${TGT${TGTID}_NAME})\n")
        math(EXPR TGTID "${TGTID} + 1")
    endwhile()
endif()

# Update the output only if different - avoid unnecessary rebuilds
file(WRITE ${MISSION_BINARY_DIR}/inc/cfe_mission_tgtnames.inc.tmp ${TGTNAMELIST})
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different
    ${MISSION_BINARY_DIR}/inc/cfe_mission_tgtnames.inc.tmp
    ${MISSION_BINARY_DIR}/inc/cfe_mission_tgtnames.inc
)
file(REMOVE ${MISSION_BINARY_DIR}/inc/cfe_mission_tgtnames.inc.tmp)

# Capture critical cache variables from the build environment so they can be
# used in custom makefiles that are invoked from here as custom targets
string(TOLOWER ${MISSION_NAME}_eds MISSION_EDS_FILE_PREFIX)
string(TOUPPER ${MISSION_NAME} MISSION_EDS_SYMBOL_PREFIX)

add_custom_command(OUTPUT 
      ${MISSION_BINARY_DIR}/inc/cfe_mission_eds_parameters.h
    COMMAND "${CMAKE_COMMAND}"
        -D TEMPLATE_FILE="cfe_mission_eds_parameters.h.in"
        -D OUTPUT_FILE=${MISSION_BINARY_DIR}/inc/cfe_mission_eds_parameters.h
        -D EDS_FILE_PREFIX=${MISSION_EDS_FILE_PREFIX}
        -D MISSION_NAME=${MISSION_NAME}
        -D EDS_SYMBOL_PREFIX=${MISSION_EDS_SYMBOL_PREFIX}
        -P export-cmake-env.cmake
    WORKING_DIRECTORY
        ${CMAKE_CURRENT_LIST_DIR}/cmake
)

add_custom_command(OUTPUT 
      ${MISSION_BINARY_DIR}/inc/cfe_mission_eds_interface_parameters.h
    COMMAND "${CMAKE_COMMAND}"
        -D TEMPLATE_FILE="cfe_mission_eds_interface_parameters.h.in"
        -D OUTPUT_FILE=${MISSION_BINARY_DIR}/inc/cfe_mission_eds_interface_parameters.h
        -D EDS_FILE_PREFIX=${MISSION_EDS_FILE_PREFIX}
        -D EDS_SYMBOL_PREFIX=${MISSION_EDS_SYMBOL_PREFIX}
        -P export-cmake-env.cmake
    WORKING_DIRECTORY
        ${CMAKE_CURRENT_LIST_DIR}/cmake
)

add_custom_target(cfe-mission-eds-headers
    DEPENDS
        ${CMAKE_BINARY_DIR}/inc/cfe_mission_eds_parameters.h
        ${CMAKE_BINARY_DIR}/inc/cfe_mission_eds_interface_parameters.h
)

# Executing the EDS tool per above custom commands is hooked into
# the pre-build process so it is done before any CPU builds.
add_dependencies(edstool-execute cfe-mission-eds-headers)
add_dependencies(mission-prebuild edstool-execute)

if (ENABLE_UNIT_TESTS)
  include(${CMAKE_CURRENT_LIST_DIR}/unit-test/mission_build.cmake)
endif(ENABLE_UNIT_TESTS)
