name: Internal Format Check

# Run on all push and pull requests
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  format-check:
    name: Run format check
    uses: cFS/workflows/.github/workflows/format-check-reusable-internal.yml@dev
